# DataXlab -> Task 1: Data Cleaning and Preprocessing

### Objective: Clean and prepare a raw dataset (with nulls, duplicates, inconsistent formats).

### Tool: Python (Pandas)

### Dataset : Mall Customer Segmentation Dataset

In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("internship_tasks/Mall_Customers.csv")

In [8]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [9]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [11]:
df.shape

(200, 5)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

## Step 1 : Identify and handle missing values

In [13]:
df.isnull()

     CustomerID  Gender    Age  Annual Income (k$)  Spending Score (1-100)
0         False   False  False               False                   False
1         False   False  False               False                   False
2         False   False  False               False                   False
3         False   False  False               False                   False
4         False   False  False               False                   False
..          ...     ...    ...                 ...                     ...
195       False   False  False               False                   False
196       False   False  False               False                   False
197       False   False  False               False                   False
198       False   False  False               False                   False
199       False   False  False               False                   False

[200 rows x 5 columns]

In [14]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

### Checked for missing or null values using df.isnull().sum(). No missing or null values rows were found in the dataset

## Step 2 : Remove duplicate rows

In [20]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

### Checked for duplicate records using df.duplicated().sum(). No duplicate rows were found in the dataset.

## Step 3 : Standardize text values

In [40]:
df["gender"] = df["gender"].str.lower()

In [42]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

### Standardized text values in the gender column by converting all entries to lowercase for consistency.

## Step 4 : Convert date formats to a consistent type

In [27]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

### Checked the dataset for date columns. No date fields were available, so date format standardization was not applicable.

## Step 5 : Rename column headers to be clean and uniform

In [29]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [30]:
df.columns = [
    'customer_id',
    'gender',
    'age',
    'annual_income',
    'spending_score'
]

In [31]:
df.columns

Index(['customer_id', 'gender', 'age', 'annual_income', 'spending_score'], dtype='object')

### Renamed column headers to a standardized format by converting them to lowercase and replacing spaces/special characters with underscores.

In [41]:
df.head()

   customer_id  gender  age  annual_income  spending_score
0            1    male   19             15              39
1            2    male   21             15              81
2            3  female   20             16               6
3            4  female   23             16              77
4            5  female   31             17              40

## Step 6 : Check and fix data types

In [43]:
df.dtypes

customer_id        int64
gender            object
age                int64
annual_income      int64
spending_score     int64
dtype: object

### Verified data types for all columns. All variables were already stored in appropriate formats, so no data type conversions were necessary.

## Final Step : Save Cleaned Dataset

In [48]:
df.to_csv("internship_tasks/cleaned_mall_customers.csv", index=False)

In [49]:
import os
print(os.path.exists("internship_tasks/cleaned_mall_customers.csv"))

True